### ISSUE TITLE
package not available in composer

### ISSUE THREAD

**Issue by kkz6** [rajathans/shiprocket-php#3]

**Comment by rajathans** [comment]
I've added the package on [packagist](https://packagist.org/packages/rajathans/shiprocket-php). You can install it using composer now.

However, please note that this package has not been updated for months now and there might be breaking changes in some APIs. Also, there are a lot of APIs I've not implemented yet, for which I'm looking for people who can contribute to this repo's development and make it more stable.

**Comment by kkz6** [comment]
Yea I could find some of the options are also not available in the package. Sure contribution can be done. I am working with your package only when the work get completed I'll come back to you to discuss about the contribution.
Thanks
